# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  docker: circleci/docker@2.0.2
  snyk: snyk/snyk@1.4.1
  kubernetes: circleci/kubernetes@1.3.0
  minikube: takescoop/minikube@1.0.1
  helm: circleci/helm@1.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
       # build the  image
     - run: docker build -t ntlaletsi70/vehicles:$CIRCLE_BRANCH .
       # push the image
     - run: docker push ntlaletsi70/vehicles:$CIRCLE_BRANCH
     - snyk/scan
 deploy:
   machine: true
   steps:
     - minikube/install
     - minikube/install-kubectl
     - helm/install-helm-client
     - minikube/start
     - run:
          name: Deployment
          command: |
            git clone git@bitbucket.org:ntlaletsi/k8s.git && cd k8s
            git fetch --prune
            git checkout feature/create_tekton_pipelines
            kubectl create namespace development
            sleep 50
            kubectl apply -f DevOps/domain/vehicles/app/deployment/app_deployment.yaml
            sleep 50
            kubectl set image deployment.apps/vehicles-web-app vehicles=ntlaletsi70/vehicles:$CIRCLE_BRANCH -n development
            sleep 50
            kubectl describe pod -n development
workflows:
  build-workflow:
    jobs:
      - build
  # deploy-workflow:
  #   jobs:
  #     - deploy
