apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app
  namespace: vehicles
spec:
  template:
    spec:
      serviceAccountName: tekton-triggers-sa
      containers:
        - image: docker.io/ntlaletsi70/vehicles:bugfix-redo_dockerfile
          imagePullPolicy: Always