apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
        - image: docker.io/ntlaletsi70/vehicles:bugfix-redo_dockerfile
          imagePullPolicy: Always
          # env:
          #   - name: TARGET
          #     value: Welcome to the Cloud-Native Summit today